name: CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  install:
    name: Install Dependencies
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: 'npm'

    - name: Install dependencies
      run: |
        npm ci
        npm ls || true

    - name: Cache node modules
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.os }}-node-22-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-22-

  audit:
    name: Security Audit
    runs-on: ubuntu-latest
    needs: install

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: 'npm'

    - name: Restore node modules
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.os }}-node-22-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-22-

    - name: Install dependencies (fallback)
      run: npm ci

    - name: Run security audit
      run: |
        npm audit --audit-level=moderate
        
    - name: Generate audit report
      run: |
        npm audit --json > audit-report.json || true
        
    - name: Upload audit report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: security-audit-report
        path: audit-report.json
        retention-days: 30

  build:
    name: Build Application
    runs-on: ubuntu-latest
    needs: install

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: 'npm'

    - name: Restore node modules
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.os }}-node-22-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-22-

    - name: Install dependencies (fallback)
      run: npm ci

    - name: Build application
      run: |
        npm run build
        npm run build-storybook

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: |
          dist/
          storybook-static/
        retention-days: 7

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: [install, build]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: 'npm'

    - name: Install Chrome
      uses: browser-actions/setup-chrome@v1

    - name: Restore node modules
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.os }}-node-22-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-22-

    - name: Install dependencies (fallback)
      run: npm ci

    - name: Install additional dependencies for testing
      run: |
        npm install -g http-server wait-on

    - name: Install Playwright browsers
      run: npx playwright install --with-deps

    - name: Clean dist directory to avoid Jest conflicts
      run: rm -rf dist/

    - name: Run unit tests
      run: |
        npm run test -- --watch=false --browsers=ChromeHeadless --code-coverage
      env:
        CI: true

    - name: Build Storybook for testing
      run: |
        npm run build-storybook
      env:
        CI: true

    - name: Start Storybook server
      run: |
        http-server storybook-static --port 6006 --silent &
        wait-on http://localhost:6006 --timeout 30000
      env:
        CI: true

    - name: Run Storybook tests
      run: |
        npm run test-storybook
      env:
        CI: true
        
    - name: Upload coverage reports
      uses: codecov/codecov-action@v4
      with:
        files: ./coverage/**/lcov.info,./coverage/storybook/lcov.info
        fail_ci_if_error: false
        name: coverage-node-22

    - name: Upload test artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-coverage-reports
        path: |
          coverage/
        retention-days: 7