name: Release Pipeline

on:
  push:
    branches: [monorepo-release]
  pull_request:
    branches: [monorepo-release]

permissions:
  contents: write
  issues: write
  pull-requests: write
  pages: write
  id-token: write

jobs:
  # Test and Build all packages
  test:
    name: Test and Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Type check
        run: npm run check-types

      - name: Build packages
        run: npm run build

      - name: Build Storybooks
        run: npm run build-storybook

  # Release NPM packages using Changesets
  release:
    name: Release NPM Packages
    if: github.ref == 'refs/heads/monorepo-release'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Build packages
        run: npm run build

      - name: Disable Husky for automated commits
        run: echo 'export HUSKY=0' >> $GITHUB_ENV

      - name: Create Release Pull Request or Publish to NPM
        id: changesets
        uses: changesets/action@v1
        with:
          publish: npm run release
          commit: "chore(release): publish packages [skip ci]"
          title: "chore(release): publish packages"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  # Deploy Storybooks to GitHub Pages
  deploy-storybooks:
    name: Deploy Storybooks
    if: github.ref == 'refs/heads/monorepo-release'
    needs: test
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Storybooks
        run: npm run build-storybook

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Create Storybook index
        run: |
          mkdir -p storybook-dist
          echo '<!DOCTYPE html>
          <html>
          <head>
            <title>Quanta Kit Design System</title>
            <style>
              body { font-family: Arial, sans-serif; max-width: 800px; margin: 50px auto; padding: 20px; }
              .section { margin: 3rem 0; }
              .link { display: block; padding: 20px; margin: 10px 0; text-decoration: none; color: #333; border-radius: 8px; }
              .storybook-link { background: #f0f8ff; border-left: 4px solid #0066cc; }
              .storybook-link:hover { background: #e6f3ff; }
              .docs-link { background: #f5f5f5; border-left: 4px solid #666; }
              .docs-link:hover { background: #e0e0e0; }
            </style>
          </head>
          <body>
            <h1>Quanta Kit Design System</h1>
            
            <div class="section">
              <h2>🏗️ Storybook Documentation</h2>
              <p>Interactive component documentation and playground</p>
              <a href="./react/" class="link storybook-link">
                <strong>React Components</strong><br>
                Storybook for React component library
              </a>
              <a href="./vue/" class="link storybook-link">
                <strong>Vue Components</strong><br>
                Storybook for Vue component library
              </a>
              <a href="./angular/" class="link storybook-link">
                <strong>Angular Components</strong><br>
                Storybook for Angular component library
              </a>
            </div>
            
            <div class="section">
              <h2>📚 Documentation Sites</h2>
              <p>Framework-specific usage examples and guides</p>
              <a href="./docs/react/" class="link docs-link">
                <strong>React Documentation</strong><br>
                Examples and usage for React components
              </a>
              <a href="./docs/vue/" class="link docs-link">
                <strong>Vue Documentation</strong><br>
                Examples and usage for Vue components
              </a>
              <a href="./docs/angular/" class="link docs-link">
                <strong>Angular Documentation</strong><br>
                Examples and usage for Angular components
              </a>
            </div>
          </body>
          </html>' > storybook-dist/index.html

      - name: Copy Storybook builds
        run: |
          cp -r packages/quanta-kit-react/storybook-static storybook-dist/react || echo "React Storybook not found"
          cp -r packages/quanta-kit-vue/storybook-static storybook-dist/vue || echo "Vue Storybook not found"
          cp -r packages/quanta-kit-angular/storybook-static storybook-dist/angular || echo "Angular Storybook not found"

      - name: Upload Storybook artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: storybook-dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  # Deploy Documentation Sites
  deploy-docs:
    name: Deploy Documentation Sites
    if: github.ref == 'refs/heads/monorepo-release'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build packages (needed for docs)
        run: npm run build

      - name: Build React docs
        run: |
          cd apps/quanta-kit-react-docs
          npm run build
          
      - name: Build Vue docs
        run: |
          cd apps/quanta-kit-vue-docs
          npm run build

      - name: Build Angular docs
        run: |
          cd apps/quanta-kit-angular-docs
          npm run build

      - name: Create docs index
        run: |
          mkdir -p docs-dist
          echo '<!DOCTYPE html>
          <html>
          <head>
            <title>Quanta Kit Design System - Documentation</title>
            <style>
              body { font-family: Arial, sans-serif; max-width: 800px; margin: 50px auto; padding: 20px; }
              .docs-link { display: block; padding: 20px; margin: 10px 0; background: #f0f8ff; text-decoration: none; color: #333; border-radius: 8px; border-left: 4px solid #0066cc; }
              .docs-link:hover { background: #e6f3ff; }
            </style>
          </head>
          <body>
            <h1>Quanta Kit Design System</h1>
            <h2>Documentation Sites</h2>
            <a href="./react/" class="docs-link">
              <strong>React Documentation</strong><br>
              Examples and usage for React components
            </a>
            <a href="./vue/" class="docs-link">
              <strong>Vue Documentation</strong><br>
              Examples and usage for Vue components
            </a>
            <a href="./angular/" class="docs-link">
              <strong>Angular Documentation</strong><br>
              Examples and usage for Angular components
            </a>
          </body>
          </html>' > docs-dist/index.html

      - name: Copy documentation builds
        run: |
          cp -r apps/quanta-kit-react-docs/out docs-dist/react || cp -r apps/quanta-kit-react-docs/dist docs-dist/react || echo "React docs not found"
          cp -r apps/quanta-kit-vue-docs/dist docs-dist/vue || echo "Vue docs not found"
          cp -r apps/quanta-kit-angular-docs/dist/quanta-kit-angular-docs docs-dist/angular || echo "Angular docs not found"

      - name: Deploy docs to main GitHub Pages (subdirectory)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs-dist
          destination_dir: docs
          keep_files: true
